version: "3.4"

services:
  node:
    container_name: data-parser-api
    build: .
    command: npm start
    restart: always
    env_file:
      - .env
    volumes:
      - .:/usr/src/data-parser-api
    ports:
      - "4014:4014"



